-- AlterTable
ALTER TABLE `DailyNutrition` ADD COLUMN `consumedCalciumMg` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `consumedCholesterolMg` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `consumedFiber` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `consumedIronMg` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `consumedMagnesiumMg` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `consumedZincMg` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `targetCalciumMg` DOUBLE NOT NULL DEFAULT 1000,
    ADD COLUMN `targetCholesterolMg` DOUBLE NOT NULL DEFAULT 300,
    ADD COLUMN `targetFiber` DOUBLE NOT NULL DEFAULT 30,
    ADD COLUMN `targetIronMg` DOUBLE NOT NULL DEFAULT 19,
    ADD COLUMN `targetMagnesiumMg` DOUBLE NOT NULL DEFAULT 440,
    ADD COLUMN `targetZincMg` DOUBLE NOT NULL DEFAULT 17;

-- AlterTable
ALTER TABLE `FoodLog` ADD COLUMN `totalCalciumMg` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `totalCholesterolMg` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `totalFiber` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `totalIronMg` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `totalMagnesiumMg` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `totalZincMg` DOUBLE NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `FoodLogItem` ADD COLUMN `calciumMg` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `cholesterolMg` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `fiberG` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `ironMg` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `magnesiumMg` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `zincMg` DOUBLE NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `Ingredient` ADD COLUMN `calciumMgPer100g` DOUBLE NULL,
    ADD COLUMN `cholesterolMgPer100g` DOUBLE NULL,
    ADD COLUMN `ironMgPer100g` DOUBLE NULL,
    ADD COLUMN `magnesiumMgPer100g` DOUBLE NULL,
    ADD COLUMN `zincMgPer100g` DOUBLE NULL;

-- AlterTable
ALTER TABLE `MealNutrition` ADD COLUMN `calciumMg` DOUBLE NULL,
    ADD COLUMN `cholesterolMg` DOUBLE NULL,
    ADD COLUMN `ironMg` DOUBLE NULL,
    ADD COLUMN `magnesiumMg` DOUBLE NULL,
    ADD COLUMN `zincMg` DOUBLE NULL;

-- AlterTable
ALTER TABLE `MealPlanDay` ADD COLUMN `targetCalciumMg` DOUBLE NOT NULL DEFAULT 1000,
    ADD COLUMN `targetCholesterolMg` DOUBLE NOT NULL DEFAULT 300,
    ADD COLUMN `targetFiber` DOUBLE NOT NULL DEFAULT 30,
    ADD COLUMN `targetIronMg` DOUBLE NOT NULL DEFAULT 19,
    ADD COLUMN `targetMagnesiumMg` DOUBLE NOT NULL DEFAULT 440,
    ADD COLUMN `targetZincMg` DOUBLE NOT NULL DEFAULT 17;
